Repository im2sh/DATABASE-PROJECT-COMP-322, pull requests merged in 2023-12, with the labels that each got.

#40 feat : 다이어리 생성 기능 추가
  .DS_Store
  phase-2/.DS_Store
  phase-3/.DS_Store
  phase-4/togaether/src/main/java/.DS_Store
  phase-4/togaether/src/main/java/com/.DS_Store
  phase-4/togaether/src/main/java/com/comp322team12/.DS_Store
  phase-4/togaether/src/main/java/com/comp322team12/together/.DS_Store
  phase-4/togaether/src/main/java/com/comp322team12/together/api/DiaryController.java
  phase-4/togaether/src/main/java/com/comp322team12/together/api/UserController.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/Diary.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/Place.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/User/User.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/contains/Contains.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/contains/ContainsId.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/request/diary/DiaryCreateRequest.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/response/place/PlaceResponse.java
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/ContainsRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/DiaryService.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/UserService.java
Labels: ✨ Feature, 📬 API

#41 feat: 일기 기능 구현
  phase-4/togaether/src/main/java/com/comp322team12/together/api/DiaryController.java
  phase-4/togaether/src/main/java/com/comp322team12/together/api/PlaceController.java
  phase-4/togaether/src/main/java/com/comp322team12/together/api/UserController.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/Diary.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/User/User.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/pet/Pet.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/pet/PetId.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/request/diary/DiaryCreateRequest.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/request/pet/PetCreateRequest.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/request/user/UserPwModificationRequest.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/response/diary/DiaryResponse.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/response/pet/PetResponse.java
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/DiaryRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/PlaceRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/DiaryService.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/PlaceService.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/UserService.java
Labels: ✨ Feature, 📬 API

#42 feat: 각 페이지 api 연결 및 diary 페이지 일부 구현
  phase-4/togaether/src/main/frontend/src/App.js
  phase-4/togaether/src/main/frontend/src/components/ChangePasswordForm.jsx
  phase-4/togaether/src/main/frontend/src/components/DiaryEntry.jsx
  phase-4/togaether/src/main/frontend/src/components/SignupForm.jsx
  phase-4/togaether/src/main/frontend/src/pages/changePassword/ChangePasswordPage.jsx
  phase-4/togaether/src/main/frontend/src/pages/diaryFeed/DiaryFeedPage.jsx
  phase-4/togaether/src/main/frontend/src/pages/home/HomePage.jsx
  phase-4/togaether/src/main/frontend/src/pages/signup/SignupPage.jsx
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/response/place/PlaceResponse.java
Labels: ✨ Feature

#49 feat: 회원가입 비관적 락으로 동시성 제어
  phase-4/togaether/build.gradle
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/Place.java
  phase-4/togaether/src/main/java/com/comp322team12/together/domain/User/User.java
  phase-4/togaether/src/main/java/com/comp322team12/together/dto/response/place/PlaceResponse.java
  phase-4/togaether/src/main/java/com/comp322team12/together/exception/user/DuplicateEmailException.java
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/BookmarkRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/PlaceRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/UserRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/PlaceService.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/UserService.java
Labels: ✨ Feature

#51 docs(Backend): Update README.md
  phase-4/togaether/src/main/java/com/docs/README.MD
Labels: 📃 Docs

#56 fix: 비밀번호 로직 수정
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/UserRepository.java
  phase-4/togaether/src/main/java/com/comp322team12/together/service/UserService.java
Labels: 👹 BugFix

#60 fix: 로컬에서 수정한 코드 push되지 않는 오류 수정
  phase-4/togaether/src/main/java/com/comp322team12/together/repository/UserRepository.java
Labels: 👹 BugFix
